const ActionTypes = {
	CLINIC_CHANGED: "CLINIC_CHANGED",
	LOAD_PRESCRIBERS: "LOAD_PRESCRIBERS",
	PRESCRIBER_CHANGED: "PRESCRIBER_CHANGED",
	LOAD_SECONDARIES: "LOAD_SECONDARIES",
	SECONDARY_CHANGED: "SECONDARY_CHANGED",
	SEND_DATA: "SEND_DATA",
	VALUE_CHANGED: "VALUE_CHANGED",
	SEND_DATA_SUCCESS:"SEND_DATA_SUCCESS"
};

export default ActionTypes;